controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    pegasus_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
      state_publish_rate: 50
      command_publish_rate: 50
      allow_partial_joints_goal: true
      constraints:
        goal_time: 0.5
        stopped_velocity_tolerance: 0.01
        joint1: { trajectory: 0.1, goal: 0.1 }
        joint2: { trajectory: 0.1, goal: 0.1 }
        joint3: { trajectory: 0.1, goal: 0.1 }
        joint4: { trajectory: 0.1, goal: 0.1 }
        joint5: { trajectory: 0.1, goal: 0.1 }
        joint6: { trajectory: 0.1, goal: 0.1 }