controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Joint State Broadcaster (required)
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 50.0

    # Arm Trajectory Controller
    pegasus_arm_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - joint1_base
        - joint2_shoulder
        - joint3_elbow
        - joint4
        - joint5_wrist
      
      command_interfaces:
        - position
      
      state_interfaces:
        - position
        - velocity
      
      constraints:
        stopped_velocity_tolerance: 0.01
        joint1_base: {trajectory: 0.1, goal: 0.1}
        joint2_shoulder: {trajectory: 0.1, goal: 0.1}
        joint3_elbow: {trajectory: 0.1, goal: 0.1}
        joint4: {trajectory: 0.1, goal: 0.1}
        joint5_wrist: {trajectory: 0.1, goal: 0.1}
      
      state_publish_rate: 50.0
      action_monitor_rate: 20.0
      
      gains:
        joint1_base: {p: 100.0, d: 10.0, i: 1.0, i_clamp: 1.0}
        joint2_shoulder: {p: 100.0, d: 10.0, i: 1.0, i_clamp: 1.0}
        joint3_elbow: {p: 100.0, d: 10.0, i: 1.0, i_clamp: 1.0}
        joint4: {p: 100.0, d: 10.0, i: 1.0, i_clamp: 1.0}
        joint5_wrist: {p: 100.0, d: 10.0, i: 1.0, i_clamp: 1.0}
      
      allow_partial_joints_goal: false
      open_loop_control: false

    # Optional: Gripper controller if you have one
    # pegasus_gripper_controller:
    #   type: gripper_controllers/GripperCommandController
    #   joints: [gripper_joint]
    #   command_interfaces: [position]
    #   state_interfaces: [position, velocity]
    #   publish_rate: 50.0
    
    
    
    
    
    
