controller_manager:
  ros__parameters:
    update_rate: 100


    pegasus_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5

        
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
