controller_manager:
  ros__parameters:
    update_rate: 100

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

pegasus_arm_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.5
      joint1:
        trajectory: 0.1
        goal: 0.05
      joint2:
        trajectory: 0.1
        goal: 0.05
      joint3:
        trajectory: 0.1
        goal: 0.05
      joint4:
        trajectory: 0.1
        goal: 0.05
      joint5:
        trajectory: 0.1
        goal: 0.05

