ompl:
  planner_configs:
    RRTConnect:
      type: geometric::RRTConnect
      range: 0.05  # The maximum distance between two states in the tree.
      max_neighbors: 10  # Maximum number of nearest neighbors to consider when building the tree.
    RRTstar:
      type: geometric::RRTstar
      range: 0.05
      max_neighbors: 10
      connection_radius: 0.1  # Connection radius for RRT*.
    PRM:
      type: geometric::PRM
      max_nearest_neighbors: 10  # Max nearest neighbors for PRM.
      max_steps: 1000  # Maximum number of steps to take in the roadmap.

  planning_pipelines:
    - ompl
  planning_interface: ompl_interface/OMPLPlanning
  pipeline_configuration:
    manipulator:
      group: manipulator
      joint_limits:
        joint1_base:
          lower: -3.1416
          upper: 3.1416
        joint2_shoulder:
          lower: -1.22173
          upper: 0.610865
        joint3_elbow:
          lower: -2.7453296096
          upper: 1.0
        joint4:
          lower: -1.309
          upper: 0.0
        joint5_wrist:
          lower: -3.1416
          upper: 3.1416
      goal_tolerance: 0.01
      start_tolerance: 0.01

  # Optional parameters for each planner configuration
  planning_time: 5.0  # Maximum time allowed for planning.
  max_attempts: 10  # Maximum number of planning attempts before stopping.
  use_sim_time: true
