controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

# MoveIt Simple Controller Manager parameters
controller_names:
  - pegasus_arm_controller

pegasus_arm_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - joint1_base
    - joint2_shoulder
    - joint3_elbow
    - joint4
    - joint5_wrist
